[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-image-bot"
version = "1.0.0"
description = "Telegram bot for AI image generation using Fal.ai"
dependencies = [
    "python-telegram-bot>=20.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = []
