[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-image-bot"
version = "1.0.0"
description = "Telegram bot for AI image generation using Fal.ai"
dependencies = [
    "python-telegram-bot==22.4",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "aiohttp>=3.12.15",
    "telegram>=0.0.1",
]

[project.optional-dependencies]
dev = []
