services:
  - type: worker
    name: telegram-image-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: BOT_USERNAME
        sync: false
    scaling:
      numInstances: 1
    autoDeploy: true