services:
  - type: background_worker
    name: telegram-image-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1